post:
  summary: Create a task
  description: Returns newly created task.
  operationId: createTask
  security:
    - cookieAuth: []
    - bearerAuth: []
  tags:
    - tasks
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/tasks/Create.yaml'
  responses:
    '200':
      description: Successfully created task
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/tasks/Task.yaml'
    '401':
      $ref: '../../components/responses/Unauthorized.yaml'
    '422':
      $ref: '../../components/responses/UnprocessableEntity.yaml'
get:
  summary: List tasks
  description: Returns a list of tasks.
  operationId: findTasks
  security:
    - cookieAuth: []
    - bearerAuth: []
  tags:
    - tasks
  parameters:
    - name: created_by
      in: query
      description: Created by
      schema:
        type: string
    - name: completed
      in: query
      description: Completed
      schema:
        type: string
    - name: q
      in: query
      description: Query
      schema:
        type: array
        items:
          type: string
    - name: per_page
      in: query
      description: Number of tasks to return per page
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
    - name: page
      in: query
      description: Page
      schema:
        type: integer
        minimum: 1
        default: 1
  responses:
    '200':
      description: Successfully returned a list of tasks
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/tasks/List.yaml'
      headers:
        Link:
          schema:
            $ref: '../../components/headers/Link.yaml'
        X-Next-Page:
          schema:
            $ref: '../../components/headers/X-Next-Page.yaml'
        X-Page:
          schema:
            $ref: '../../components/headers/X-Page.yaml'
        X-Per-Page:
          schema:
            $ref: '../../components/headers/X-Per-Page.yaml'
        X-Prev-Page:
          schema:
            $ref: '../../components/headers/X-Prev-Page.yaml'
        X-Total:
          schema:
            $ref: '../../components/headers/X-Total.yaml'
        X-Total-Pages:
          schema:
            $ref: '../../components/headers/X-Total-Pages.yaml'
    '401':
      $ref: '../../components/responses/Unauthorized.yaml'
