with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/alexferl/echo-boilerplate/data:
    interfaces:
      Mapper:
  github.com/alexferl/echo-boilerplate/handlers/tasks:
    interfaces:
      IModel:
