quiet: False
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
outpkg: mocks
dir: mocks/
packages:
  github.com/alexferl/echo-boilerplate/data:
    interfaces:
      IMapper:


#with-expecter: True
#inpackage: True
#dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
#mockname: "{{.InterfaceName}}"
#outpkg: "{{.PackageName}}"
#filename: "{{.InterfaceName}}.go"
