with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/alexferl/echo-boilerplate/handlers:
    interfaces:
      PersonalAccessTokenService:
      TaskService:
      UserService:
  github.com/alexferl/echo-boilerplate/services:
    interfaces:
      PersonalAccessTokenMapper:
      TaskMapper:
      UserMapper:
