// Code generated by mockery v2.42.0. DO NOT EDIT.

package handlers

import (
	context "context"

	models "github.com/alexferl/echo-boilerplate/models"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, id, data
func (_m *MockTaskService) Create(ctx context.Context, id string, data *models.Task) (*models.Task, error) {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Task) (*models.Task, error)); ok {
		return rf(ctx, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Task) *models.Task); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.Task) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data *models.Task
func (_e *MockTaskService_Expecter) Create(ctx interface{}, id interface{}, data interface{}) *MockTaskService_Create_Call {
	return &MockTaskService_Create_Call{Call: _e.mock.On("Create", ctx, id, data)}
}

func (_c *MockTaskService_Create_Call) Run(run func(ctx context.Context, id string, data *models.Task)) *MockTaskService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.Task))
	})
	return _c
}

func (_c *MockTaskService_Create_Call) Return(_a0 *models.Task, _a1 error) *MockTaskService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_Create_Call) RunAndReturn(run func(context.Context, string, *models.Task) (*models.Task, error)) *MockTaskService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, data
func (_m *MockTaskService) Delete(ctx context.Context, id string, data *models.Task) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Task) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data *models.Task
func (_e *MockTaskService_Expecter) Delete(ctx interface{}, id interface{}, data interface{}) *MockTaskService_Delete_Call {
	return &MockTaskService_Delete_Call{Call: _e.mock.On("Delete", ctx, id, data)}
}

func (_c *MockTaskService_Delete_Call) Run(run func(ctx context.Context, id string, data *models.Task)) *MockTaskService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.Task))
	})
	return _c
}

func (_c *MockTaskService_Delete_Call) Return(_a0 error) *MockTaskService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_Delete_Call) RunAndReturn(run func(context.Context, string, *models.Task) error) *MockTaskService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, params
func (_m *MockTaskService) Find(ctx context.Context, params *models.TaskSearchParams) (int64, models.Tasks, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 int64
	var r1 models.Tasks
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TaskSearchParams) (int64, models.Tasks, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.TaskSearchParams) int64); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.TaskSearchParams) models.Tasks); ok {
		r1 = rf(ctx, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(models.Tasks)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *models.TaskSearchParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTaskService_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockTaskService_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - params *models.TaskSearchParams
func (_e *MockTaskService_Expecter) Find(ctx interface{}, params interface{}) *MockTaskService_Find_Call {
	return &MockTaskService_Find_Call{Call: _e.mock.On("Find", ctx, params)}
}

func (_c *MockTaskService_Find_Call) Run(run func(ctx context.Context, params *models.TaskSearchParams)) *MockTaskService_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.TaskSearchParams))
	})
	return _c
}

func (_c *MockTaskService_Find_Call) Return(_a0 int64, _a1 models.Tasks, _a2 error) *MockTaskService_Find_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTaskService_Find_Call) RunAndReturn(run func(context.Context, *models.TaskSearchParams) (int64, models.Tasks, error)) *MockTaskService_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, id
func (_m *MockTaskService) Read(ctx context.Context, id string) (*models.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockTaskService_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) Read(ctx interface{}, id interface{}) *MockTaskService_Read_Call {
	return &MockTaskService_Read_Call{Call: _e.mock.On("Read", ctx, id)}
}

func (_c *MockTaskService_Read_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_Read_Call) Return(_a0 *models.Task, _a1 error) *MockTaskService_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_Read_Call) RunAndReturn(run func(context.Context, string) (*models.Task, error)) *MockTaskService_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockTaskService) Update(ctx context.Context, id string, data *models.Task) (*models.Task, error) {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Task) (*models.Task, error)); ok {
		return rf(ctx, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Task) *models.Task); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.Task) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data *models.Task
func (_e *MockTaskService_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockTaskService_Update_Call {
	return &MockTaskService_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockTaskService_Update_Call) Run(run func(ctx context.Context, id string, data *models.Task)) *MockTaskService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.Task))
	})
	return _c
}

func (_c *MockTaskService_Update_Call) Return(_a0 *models.Task, _a1 error) *MockTaskService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_Update_Call) RunAndReturn(run func(context.Context, string, *models.Task) (*models.Task, error)) *MockTaskService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
