// Code generated by mockery v2.42.0. DO NOT EDIT.

package services

import (
	context "context"

	models "github.com/alexferl/echo-boilerplate/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserMapper is an autogenerated mock type for the UserMapper type
type MockUserMapper struct {
	mock.Mock
}

type MockUserMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserMapper) EXPECT() *MockUserMapper_Expecter {
	return &MockUserMapper_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, model
func (_m *MockUserMapper) Create(ctx context.Context, model *models.User) (*models.User, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = rf(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserMapper_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserMapper_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.User
func (_e *MockUserMapper_Expecter) Create(ctx interface{}, model interface{}) *MockUserMapper_Create_Call {
	return &MockUserMapper_Create_Call{Call: _e.mock.On("Create", ctx, model)}
}

func (_c *MockUserMapper_Create_Call) Run(run func(ctx context.Context, model *models.User)) *MockUserMapper_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserMapper_Create_Call) Return(_a0 *models.User, _a1 error) *MockUserMapper_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserMapper_Create_Call) RunAndReturn(run func(context.Context, *models.User) (*models.User, error)) *MockUserMapper_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter, limit, skip
func (_m *MockUserMapper) Find(ctx context.Context, filter interface{}, limit int, skip int) (int64, models.Users, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 int64
	var r1 models.Users
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, int, int) (int64, models.Users, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, int, int) int64); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, int, int) models.Users); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(models.Users)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, interface{}, int, int) error); ok {
		r2 = rf(ctx, filter, limit, skip)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserMapper_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockUserMapper_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - limit int
//   - skip int
func (_e *MockUserMapper_Expecter) Find(ctx interface{}, filter interface{}, limit interface{}, skip interface{}) *MockUserMapper_Find_Call {
	return &MockUserMapper_Find_Call{Call: _e.mock.On("Find", ctx, filter, limit, skip)}
}

func (_c *MockUserMapper_Find_Call) Run(run func(ctx context.Context, filter interface{}, limit int, skip int)) *MockUserMapper_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUserMapper_Find_Call) Return(_a0 int64, _a1 models.Users, _a2 error) *MockUserMapper_Find_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserMapper_Find_Call) RunAndReturn(run func(context.Context, interface{}, int, int) (int64, models.Users, error)) *MockUserMapper_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: ctx, filter
func (_m *MockUserMapper) FindOne(ctx context.Context, filter interface{}) (*models.User, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) (*models.User, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) *models.User); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserMapper_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockUserMapper_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
func (_e *MockUserMapper_Expecter) FindOne(ctx interface{}, filter interface{}) *MockUserMapper_FindOne_Call {
	return &MockUserMapper_FindOne_Call{Call: _e.mock.On("FindOne", ctx, filter)}
}

func (_c *MockUserMapper_FindOne_Call) Run(run func(ctx context.Context, filter interface{})) *MockUserMapper_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserMapper_FindOne_Call) Return(_a0 *models.User, _a1 error) *MockUserMapper_FindOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserMapper_FindOne_Call) RunAndReturn(run func(context.Context, interface{}) (*models.User, error)) *MockUserMapper_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, model
func (_m *MockUserMapper) Update(ctx context.Context, model *models.User) (*models.User, error) {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return rf(ctx, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = rf(ctx, model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = rf(ctx, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserMapper_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserMapper_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.User
func (_e *MockUserMapper_Expecter) Update(ctx interface{}, model interface{}) *MockUserMapper_Update_Call {
	return &MockUserMapper_Update_Call{Call: _e.mock.On("Update", ctx, model)}
}

func (_c *MockUserMapper_Update_Call) Run(run func(ctx context.Context, model *models.User)) *MockUserMapper_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockUserMapper_Update_Call) Return(_a0 *models.User, _a1 error) *MockUserMapper_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserMapper_Update_Call) RunAndReturn(run func(context.Context, *models.User) (*models.User, error)) *MockUserMapper_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserMapper creates a new instance of MockUserMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserMapper {
	mock := &MockUserMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
