type: object
additionalProperties: false
required:
  - id
  - completed
  - completed_at
  - completed_by
  - created_at
  - created_by
  - title
  - updated_at
  - updated_by
properties:
  id:
    type: string
    description: Unique identifier for this object
    example: '1'
  completed:
    type: boolean
    example: true
  completed_at:
    type: string
    format: date-time
    description: Task completion date time
    example: '2022-11-13T07:12:33.017Z'
    nullable: true
  completed_by:
    type: object
    nullable: true
    allOf:
      - $ref: '../users/Ref.yaml'
  created_at:
    type: string
    format: date-time
    description: Task creation date time
    example: '2022-11-12T14:54:18.103Z'
    nullable: true
  created_by:
    $ref: '../users/Ref.yaml'
  title:
    type: string
    description: The title of the task
    example: My Task
  updated_at:
    type: string
    format: date-time
    description: Task update date time
    example: '2022-11-12T14:58:33.409Z'
    nullable: true
  updated_by:
    type: object
    nullable: true
    allOf:
      - $ref: '../users/Ref.yaml'
